name: " Pedir Funcionalidad"
description: Crea un nuevo pedido de funcionalidad
title: "- <title>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Descripci贸n"
      description: Introduzca una breve explicaci贸n de la funcionalidad
      placeholder: Explicaci贸n clara y breve de la funcionalidad
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Ejemplo B谩sico"
      description: Indica algunos ejemplos de la funcionalidad
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Impacto"
      description: Indique el impacto que tendr铆a la implementaci贸n de la funcionalidad
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Capturas de pantalla"
      description: Si es necesario, a帽ade capturas de pantalla 
      placeholder: A帽ada im谩genes en el formato de Markdown -> ![Descripcion](linkImagen) 
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: "Informaci贸n extra"
      description: Si es necesario, indique alguna informaci贸n extra
    validations:
      required: false
